### ISSUE TITLE
Check that `from` is before `to`

### ISSUE THREAD

**Issue by xoco70** [dcasia/nova-range-input-filter#7]
Hi, 

Maybe an interesting feature is to check that the first date is before the next date. 

That is one of the most valuable feature when having a field grouping 2 dates.

**Comment by milewski** [comment]
Can you add this? should be very simple, just need to add an option to send the minDate / maxDate https://flatpickr.js.org/options/

**Comment by xoco70** [comment]
I'll give it a look, but it is a non blocking issue for me, I'd rather work on the dashboard / chartjs issue that is much more important for me!

**Comment by milewski** [comment]
@xoco70  im almost done with a new version that will fix that issue

**Comment by xoco70** [comment]
Will try to make a trending card widget if I have the time
